### ISSUE TITLE
tqdm fails in pytest

### ISSUE THREAD

**Issue by altendky** [Julian/venvs#49]
When running in pytest, even with `-s`, tqdm ends up trying to write to a `_io.BytesIO`.  When running `convergeenvs` directly it is an `open file '<stderr>', mode 'w'`.  Ah yes, only broken in py2/pypy2.

https://travis-ci.org/Julian/mkenv/jobs/412040805#L568
```python-traceback
Traceback (most recent call last):
  File "/opt/python/2.7.14/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/travis/build/Julian/mkenv/.tox/py27/lib/python2.7/site-packages/mkenv/tests/test_converge.py", line 69, in test_it_converges_existing_virtualenvs
    self.run_cli([])
  File "/home/travis/build/Julian/mkenv/.tox/py27/lib/python2.7/site-packages/mkenv/tests/utils.py", line 88, in run_cli
    catch_exceptions=False,
  File "/home/travis/build/Julian/mkenv/.tox/py27/lib/python2.7/site-packages/click/testing.py", line 279, in invoke
    prog_name=self.get_default_prog_name(cli), **extra)
  File "/home/travis/build/Julian/mkenv/.tox/py27/lib/python2.7/site-packages/mkenv/tests/utils.py", line 119, in main
    real_main.main(*args, **kwargs)
  File "/home/travis/build/Julian/mkenv/.tox/py27/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/travis/build/Julian/mkenv/.tox/py27/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/travis/build/Julian/mkenv/.tox/py27/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/travis/build/Julian/mkenv/.tox/py27/lib/python2.7/site-packages/mkenv/converge.py", line 47, in main
    progress = tqdm(contents["virtualenv"].items())
  File "/home/travis/build/Julian/mkenv/.tox/py27/lib/python2.7/site-packages/tqdm/_tqdm.py", line 859, in __init__
    self.moveto(abs(self.pos))
  File "/home/travis/build/Julian/mkenv/.tox/py27/lib/python2.7/site-packages/tqdm/_tqdm.py", line 1197, in moveto
    self.fp.write(_unicode('\n' * n + _term_move_up() * -n))
exceptions.TypeError: 'unicode' does not have the buffer interface
```

**Comment by Julian** [comment]
Hm I see the failing build, but how's py.test involved? You're running py test locally and seeing the same error?

**Comment by altendky** [comment]
Err, yeah, that again.  Anyways, yes I'm running pytest for whatever probably not great reason, but also tox (so trial).  They provide an `io.BytesIO` for tqdm to write to and it doesn't like that.

https://github.com/tqdm/tqdm/issues/589

I'm making progress on a change for them to consider, but not quite there.

**Comment by altendky** [comment]
:[ now it's just trying to do various i/o on closed files.  i think similar to what you worked around somewhere in filesystems...  have to dig more later.

**Comment by Julian** [comment]
Ech, yeah, this looks like tqdm's issue to fix unfortunately. Left a comment there.
